#ifdef TRAVERSABILITY_TOOLKIT__ADAPTERS__CV
#define TRAVERSABILITY_TOOLKIT__ADAPTERS__CV
#include "native_adapters/NavigationOccupancyGrid_CvMat.hpp"
#include "native_adapters/SensorMsgsImage_CvMat.hpp"
#endif // TRAVERSABILITY_TOOLKIT__ADAPTERS__CV