name: Ubuntu 22.04 Iron Build

on:
  pull_request:
  push:
    branches:
      - iron

jobs:
  Build:
    runs-on: self-hosted
    container:
      image: osrf/ros:iron-desktop-full-jammy

    steps:
    - name: Update Apt cache
      run: apt update

    - name: Install packages from Apt
      run: apt install -y python3-pip lcov bzip2

    - name: Install packages from PIP
      run: python3 -m pip install colcon-lcov-result colcon-coveragepy-result

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build & Test
      uses: ros-tooling/action-ros-ci@0.3.5
      with:
        target-ros2-distro: iron
        import-token: ${{ secrets.GITHUB_TOKEN }}
        vcs-repo-file-url: "${{ github.workspace }}/iron.repos"

    - name: Compress Logs
      run: tar -jcvf log.tar.tbz2 ros_ws/log
    
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: log.tar.tbz2
        compression-level: 0
